root = "."

tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api/"

bin = "tmp/main"

full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"

exclude_dir = ["tmp"]

exclude_file = []

include_file = []

delay = 1000

kill_delay = 500

log = "build-errors.log"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true